[package]
name = "mesher"
version = "0.1.0"
authors = ["Nic Hartley <nic@cybers.eco>"]
edition = "2018"

[[bin]]
name = "mesher-node"
required-features = ["node"]

[[example]]
name = "send"
required-features = ["node"]

[[example]]
name = "recv"
required-features = ["node"]

[features]
default = []
send = []
receive = []
node = []

[dependencies]
